version: '3.5'

services:
  api-gateway-lambda-go-example:
    image: tutumi/aws-sam-local-api
    environment:
      - AWS_ACCESS_KEY_ID=anykey
      - AWS_SECRET_ACCESS_KEY=anysecretkey
    env_file: .env
    volumes:
      - "./template.yml:/home/sam/template.yml"
      - "./bin/linux_amd64:/home/sam/bin/linux_amd64"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "3000:3000"
    command: local start-api --host 0.0.0.0 --docker-volume-basedir "${PWD}/bin/linux_amd64" --docker-network teste_network --skip-pull-image
    depends_on:
      - localstack
    networks:
      - dev

  localstack:
    image: localstack/localstack:0.10.6
    environment:
      - SERVICES=sqs
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - ./localstack_setup:/docker-entrypoint-initaws.d/
    ports:
      - "4576:4576"
    networks:
      - dev

networks:
  dev:
    name: teste_network

